[versions]
compileSdk = "36"
googleServices = "4.4.4"
gradle = "8.13.2"
minSdk = "33"
targetSdk = "36"
agp = "8.13.2"
googleGmsServices = "4.4.4"
appcompat = "1.7.1"
material = "1.13.0"
webkit = "1.15.0"
swiperefreshlayout = "1.2.0"
vectordrawableAnimated = "1.2.0"
junit = "4.13.2"
androidxTestExtJunit = "1.3.0"
espressoCore = "3.7.0"
googleMlkitTextRecognition = "16.0.1"

[libraries]
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
androidx-webkit = { group = "androidx.webkit", name = "webkit", version.ref = "webkit" }
androidx-swiperefreshlayout = { group = "androidx.swiperefreshlayout", name = "swiperefreshlayout", version.ref = "swiperefreshlayout" }
androidx-vectordrawable-animated = { group = "androidx.vectordrawable", name = "vectordrawable-animated", version.ref = "vectordrawableAnimated" }
google-services = { module = "com.google.gms:google-services", version.ref = "googleServices" }
gradle = { module = "com.android.tools.build:gradle", version.ref = "gradle" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-test-ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "androidxTestExtJunit" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
google-mlkit-text-recognition = { group = "com.google.mlkit", name = "text-recognition", version.ref = "googleMlkitTextRecognition" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
google-gms-google-services = { id = "com.google.gms.google-services", version.ref = "googleGmsServices" }